apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 7000
    targetPort: 5173
    nodePort: 30033
    protocol: TCP
  selector:
    app: react-app
